/**
 * Mock data để demo app khi chưa kết nối Supabase
 */

export const MOCK_DEPARTMENTS = [
  { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG', description: 'Phát triển phần mềm' },
  { id: 'dept-2', name: 'Kinh doanh - Sales', code: 'SALES', description: 'Kinh doanh bán hàng' },
  { id: 'dept-3', name: 'Marketing', code: 'MKT', description: 'Tiếp thị truyền thông' },
  { id: 'dept-4', name: 'Nhân sự - HR', code: 'HR', description: 'Quản lý nguồn nhân lực' },
  { id: 'dept-5', name: 'Tài chính - Finance', code: 'FIN', description: 'Tài chính kế toán' },
  { id: 'dept-6', name: 'Thiết kế - Design', code: 'DESIGN', description: 'Thiết kế sản phẩm và UX' },
  { id: 'dept-7', name: 'Sản phẩm - Product', code: 'PROD', description: 'Quản lý sản phẩm' },
]

export const MOCK_DESIGNATIONS = [
  { id: 'des-1', title: 'Kỹ sư phần mềm', department_id: 'dept-1', level: 2 },
  { id: 'des-2', title: 'Kỹ sư phần mềm cao cấp', department_id: 'dept-1', level: 3 },
  { id: 'des-3', title: 'Trưởng nhóm kỹ thuật', department_id: 'dept-1', level: 4 },
  { id: 'des-4', title: 'Quản lý kỹ thuật', department_id: 'dept-1', level: 5 },
  { id: 'des-5', title: 'Chuyên viên kinh doanh', department_id: 'dept-2', level: 2 },
  { id: 'des-6', title: 'Quản lý kinh doanh', department_id: 'dept-2', level: 5 },
  { id: 'des-7', title: 'Chuyên viên Marketing', department_id: 'dept-3', level: 2 },
  { id: 'des-8', title: 'Chuyên viên nhân sự', department_id: 'dept-4', level: 2 },
  { id: 'des-9', title: 'Quản lý nhân sự', department_id: 'dept-4', level: 5 },
  { id: 'des-10', title: 'Chuyên viên phân tích tài chính', department_id: 'dept-5', level: 2 },
  { id: 'des-11', title: 'Thiết kế trải nghiệm người dùng (UX)', department_id: 'dept-6', level: 2 },
  { id: 'des-12', title: 'Quản lý sản phẩm', department_id: 'dept-7', level: 4 },
]

const avatarBase = 'https://api.dicebear.com/9.x/notionists/svg?seed='

export const MOCK_EMPLOYEES = [
  {
    id: 'emp-1', employee_id: 'EMP-001',
    full_name: 'Nguyễn Văn An', email: 'an.nguyen@peoplehub.vn',
    phone: '0901234567', avatar_url: avatarBase + 'AnNguyen',
    department_id: 'dept-1', designation_id: 'des-3',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'male', date_of_birth: '1990-05-15', date_of_joining: '2020-03-01',
    bio: 'Trưởng nhóm kỹ thuật với 8 năm kinh nghiệm phát triển hệ thống phân tán.',
    departments: { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG' },
    designations: { id: 'des-3', title: 'Trưởng nhóm kỹ thuật', level: 4 },
  },
  {
    id: 'emp-2', employee_id: 'EMP-002',
    full_name: 'Trần Thị Bích', email: 'bich.tran@peoplehub.vn',
    phone: '0912345678', avatar_url: avatarBase + 'BichTran',
    department_id: 'dept-4', designation_id: 'des-9',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'female', date_of_birth: '1988-11-20', date_of_joining: '2018-07-15',
    bio: 'Quản lý nhân sự với hơn 10 năm kinh nghiệm quản lý nguồn nhân lực.',
    departments: { id: 'dept-4', name: 'Nhân sự - HR', code: 'HR' },
    designations: { id: 'des-9', title: 'Quản lý nhân sự', level: 5 },
  },
  {
    id: 'emp-3', employee_id: 'EMP-003',
    full_name: 'Lê Hoàng Minh', email: 'minh.le@peoplehub.vn',
    phone: '0923456789', avatar_url: avatarBase + 'MinhLe',
    department_id: 'dept-1', designation_id: 'des-1',
    status: 'onboarding', work_type: 'full-time', work_location: 'TP.HCM Office',
    gender: 'male', date_of_birth: '1998-03-10', date_of_joining: '2024-11-01',
    bio: 'Kỹ sư phần mềm mới tốt nghiệp, đam mê React và Node.js.',
    departments: { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG' },
    designations: { id: 'des-1', title: 'Kỹ sư phần mềm', level: 2 },
  },
  {
    id: 'emp-4', employee_id: 'EMP-004',
    full_name: 'Phạm Thuỳ Linh', email: 'linh.pham@peoplehub.vn',
    phone: '0934567890', avatar_url: avatarBase + 'LinhPham',
    department_id: 'dept-6', designation_id: 'des-11',
    status: 'active', work_type: 'full-time', work_location: 'Remote',
    gender: 'female', date_of_birth: '1995-08-22', date_of_joining: '2021-04-01',
    bio: 'Thiết kế UX chuyên về thiết kế sản phẩm và hệ thống thiết kế.',
    departments: { id: 'dept-6', name: 'Thiết kế - Design', code: 'DESIGN' },
    designations: { id: 'des-11', title: 'Thiết kế trải nghiệm người dùng (UX)', level: 2 },
  },
  {
    id: 'emp-5', employee_id: 'EMP-005',
    full_name: 'Hoàng Đức Thành', email: 'thanh.hoang@peoplehub.vn',
    phone: '0945678901', avatar_url: avatarBase + 'ThanhHoang',
    department_id: 'dept-7', designation_id: 'des-12',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'male', date_of_birth: '1992-01-30', date_of_joining: '2019-09-15',
    bio: 'Quản lý sản phẩm định hướng dữ liệu với kinh nghiệm B2B SaaS.',
    departments: { id: 'dept-7', name: 'Sản phẩm - Product', code: 'PROD' },
    designations: { id: 'des-12', title: 'Quản lý sản phẩm', level: 4 },
  },
  {
    id: 'emp-6', employee_id: 'EMP-006',
    full_name: 'Võ Khánh Huyền', email: 'huyen.vo@peoplehub.vn',
    phone: '0956789012', avatar_url: avatarBase + 'HuyenVo',
    department_id: 'dept-3', designation_id: 'des-7',
    status: 'active', work_type: 'full-time', work_location: 'TP.HCM Office',
    gender: 'female', date_of_birth: '1997-06-14', date_of_joining: '2022-01-10',
    bio: 'Chuyên viên Marketing chuyên về digital marketing và SEO.',
    departments: { id: 'dept-3', name: 'Marketing', code: 'MKT' },
    designations: { id: 'des-7', title: 'Chuyên viên Marketing', level: 2 },
  },
  {
    id: 'emp-7', employee_id: 'EMP-007',
    full_name: 'Đỗ Quang Hải', email: 'hai.do@peoplehub.vn',
    phone: '0967890123', avatar_url: avatarBase + 'HaiDo',
    department_id: 'dept-1', designation_id: 'des-2',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'male', date_of_birth: '1993-12-05', date_of_joining: '2020-08-01',
    bio: 'Kỹ sư cao cấp chuyên về backend microservices và Kubernetes.',
    departments: { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG' },
    designations: { id: 'des-2', title: 'Kỹ sư phần mềm cao cấp', level: 3 },
  },
  {
    id: 'emp-8', employee_id: 'EMP-008',
    full_name: 'Bùi Thị Lan', email: 'lan.bui@peoplehub.vn',
    phone: '0978901234', avatar_url: avatarBase + 'LanBui',
    department_id: 'dept-5', designation_id: 'des-10',
    status: 'terminated', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'female', date_of_birth: '1991-04-18', date_of_joining: '2019-03-01',
    date_of_termination: '2024-06-30',
    bio: 'Chuyên viên phân tích tài chính với nền tảng kinh tế vĩ mô.',
    departments: { id: 'dept-5', name: 'Tài chính - Finance', code: 'FIN' },
    designations: { id: 'des-10', title: 'Chuyên viên phân tích tài chính', level: 2 },
  },
]
