/**
 * Mock data để demo app khi chưa kết nối Supabase
 */

export const MOCK_DEPARTMENTS = [
  { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG', description: 'Phát triển phần mềm' },
  { id: 'dept-2', name: 'Kinh doanh - Sales', code: 'SALES', description: 'Kinh doanh bán hàng' },
  { id: 'dept-3', name: 'Marketing', code: 'MKT', description: 'Tiếp thị truyền thông' },
  { id: 'dept-4', name: 'Nhân sự - HR', code: 'HR', description: 'Quản lý nguồn nhân lực' },
  { id: 'dept-5', name: 'Tài chính - Finance', code: 'FIN', description: 'Tài chính kế toán' },
  { id: 'dept-6', name: 'Thiết kế - Design', code: 'DESIGN', description: 'Thiết kế sản phẩm và UX' },
  { id: 'dept-7', name: 'Sản phẩm - Product', code: 'PROD', description: 'Quản lý sản phẩm' },
]

export const MOCK_DESIGNATIONS = [
  { id: 'des-1', title: 'Software Engineer', department_id: 'dept-1', level: 2 },
  { id: 'des-2', title: 'Senior Software Engineer', department_id: 'dept-1', level: 3 },
  { id: 'des-3', title: 'Tech Lead', department_id: 'dept-1', level: 4 },
  { id: 'des-4', title: 'Engineering Manager', department_id: 'dept-1', level: 5 },
  { id: 'des-5', title: 'Sales Executive', department_id: 'dept-2', level: 2 },
  { id: 'des-6', title: 'Sales Manager', department_id: 'dept-2', level: 5 },
  { id: 'des-7', title: 'Marketing Specialist', department_id: 'dept-3', level: 2 },
  { id: 'des-8', title: 'HR Specialist', department_id: 'dept-4', level: 2 },
  { id: 'des-9', title: 'HR Manager', department_id: 'dept-4', level: 5 },
  { id: 'des-10', title: 'Financial Analyst', department_id: 'dept-5', level: 2 },
  { id: 'des-11', title: 'UX Designer', department_id: 'dept-6', level: 2 },
  { id: 'des-12', title: 'Product Manager', department_id: 'dept-7', level: 4 },
]

const avatarBase = 'https://api.dicebear.com/9.x/notionists/svg?seed='

export const MOCK_EMPLOYEES = [
  {
    id: 'emp-1', employee_id: 'EMP-001',
    full_name: 'Nguyễn Văn An', email: 'an.nguyen@peoplehub.vn',
    phone: '0901234567', avatar_url: avatarBase + 'AnNguyen',
    department_id: 'dept-1', designation_id: 'des-3',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'male', date_of_birth: '1990-05-15', date_of_joining: '2020-03-01',
    bio: 'Tech Lead với 8 năm kinh nghiệm phát triển hệ thống phân tán.',
    departments: { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG' },
    designations: { id: 'des-3', title: 'Tech Lead', level: 4 },
  },
  {
    id: 'emp-2', employee_id: 'EMP-002',
    full_name: 'Trần Thị Bích', email: 'bich.tran@peoplehub.vn',
    phone: '0912345678', avatar_url: avatarBase + 'BichTran',
    department_id: 'dept-4', designation_id: 'des-9',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'female', date_of_birth: '1988-11-20', date_of_joining: '2018-07-15',
    bio: 'HR Manager với hơn 10 năm kinh nghiệm quản lý nhân sự.',
    departments: { id: 'dept-4', name: 'Nhân sự - HR', code: 'HR' },
    designations: { id: 'des-9', title: 'HR Manager', level: 5 },
  },
  {
    id: 'emp-3', employee_id: 'EMP-003',
    full_name: 'Lê Hoàng Minh', email: 'minh.le@peoplehub.vn',
    phone: '0923456789', avatar_url: avatarBase + 'MinhLe',
    department_id: 'dept-1', designation_id: 'des-1',
    status: 'onboarding', work_type: 'full-time', work_location: 'TP.HCM Office',
    gender: 'male', date_of_birth: '1998-03-10', date_of_joining: '2024-11-01',
    bio: 'Software Engineer mới tốt nghiệp, đam mê React và Node.js.',
    departments: { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG' },
    designations: { id: 'des-1', title: 'Software Engineer', level: 2 },
  },
  {
    id: 'emp-4', employee_id: 'EMP-004',
    full_name: 'Phạm Thuỳ Linh', email: 'linh.pham@peoplehub.vn',
    phone: '0934567890', avatar_url: avatarBase + 'LinhPham',
    department_id: 'dept-6', designation_id: 'des-11',
    status: 'active', work_type: 'full-time', work_location: 'Remote',
    gender: 'female', date_of_birth: '1995-08-22', date_of_joining: '2021-04-01',
    bio: 'UX Designer chuyên về product design và design systems.',
    departments: { id: 'dept-6', name: 'Thiết kế - Design', code: 'DESIGN' },
    designations: { id: 'des-11', title: 'UX Designer', level: 2 },
  },
  {
    id: 'emp-5', employee_id: 'EMP-005',
    full_name: 'Hoàng Đức Thành', email: 'thanh.hoang@peoplehub.vn',
    phone: '0945678901', avatar_url: avatarBase + 'ThanhHoang',
    department_id: 'dept-7', designation_id: 'des-12',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'male', date_of_birth: '1992-01-30', date_of_joining: '2019-09-15',
    bio: 'Product Manager định hướng dữ liệu với kinh nghiệm B2B SaaS.',
    departments: { id: 'dept-7', name: 'Sản phẩm - Product', code: 'PROD' },
    designations: { id: 'des-12', title: 'Product Manager', level: 4 },
  },
  {
    id: 'emp-6', employee_id: 'EMP-006',
    full_name: 'Võ Khánh Huyền', email: 'huyen.vo@peoplehub.vn',
    phone: '0956789012', avatar_url: avatarBase + 'HuyenVo',
    department_id: 'dept-3', designation_id: 'des-7',
    status: 'active', work_type: 'full-time', work_location: 'TP.HCM Office',
    gender: 'female', date_of_birth: '1997-06-14', date_of_joining: '2022-01-10',
    bio: 'Marketing Specialist chuyên về digital marketing và SEO.',
    departments: { id: 'dept-3', name: 'Marketing', code: 'MKT' },
    designations: { id: 'des-7', title: 'Marketing Specialist', level: 2 },
  },
  {
    id: 'emp-7', employee_id: 'EMP-007',
    full_name: 'Đỗ Quang Hải', email: 'hai.do@peoplehub.vn',
    phone: '0967890123', avatar_url: avatarBase + 'HaiDo',
    department_id: 'dept-1', designation_id: 'des-2',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'male', date_of_birth: '1993-12-05', date_of_joining: '2020-08-01',
    bio: 'Senior Engineer chuyên về backend microservices và Kubernetes.',
    departments: { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG' },
    designations: { id: 'des-2', title: 'Senior Software Engineer', level: 3 },
  },
  {
    id: 'emp-8', employee_id: 'EMP-008',
    full_name: 'Bùi Thị Lan', email: 'lan.bui@peoplehub.vn',
    phone: '0978901234', avatar_url: avatarBase + 'LanBui',
    department_id: 'dept-5', designation_id: 'des-10',
    status: 'terminated', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'female', date_of_birth: '1991-04-18', date_of_joining: '2019-03-01',
    date_of_termination: '2024-06-30',
    bio: 'Financial Analyst với nền tảng kinh tế vĩ mô và phân tích tài chính.',
    departments: { id: 'dept-5', name: 'Tài chính - Finance', code: 'FIN' },
    designations: { id: 'des-10', title: 'Financial Analyst', level: 2 },
  },
  {
    id: 'emp-9', employee_id: 'EMP-009',
    full_name: 'Ngô Minh Khoa', email: 'khoa.ngo@peoplehub.vn',
    phone: '0989012345', avatar_url: avatarBase + 'KhoaNgo',
    department_id: 'dept-2', designation_id: 'des-5',
    status: 'active', work_type: 'full-time', work_location: 'TP.HCM Office',
    gender: 'male', date_of_birth: '1994-09-25', date_of_joining: '2021-11-15',
    bio: 'Sales Executive với track record đạt 150% KPI liên tục 2 năm.',
    departments: { id: 'dept-2', name: 'Kinh doanh - Sales', code: 'SALES' },
    designations: { id: 'des-5', title: 'Sales Executive', level: 2 },
  },
  {
    id: 'emp-10', employee_id: 'EMP-010',
    full_name: 'Trịnh Thu Hà', email: 'ha.trinh@peoplehub.vn',
    phone: '0990123456', avatar_url: avatarBase + 'HaTrinh',
    department_id: 'dept-4', designation_id: 'des-8',
    status: 'onboarding', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'female', date_of_birth: '1999-02-08', date_of_joining: '2025-01-06',
    bio: 'HR Specialist mới, có kinh nghiệm tuyển dụng IT.',
    departments: { id: 'dept-4', name: 'Nhân sự - HR', code: 'HR' },
    designations: { id: 'des-8', title: 'HR Specialist', level: 2 },
  },
  {
    id: 'emp-11', employee_id: 'EMP-011',
    full_name: 'Phan Thanh Long', email: 'long.phan@peoplehub.vn',
    phone: '0901234568', avatar_url: avatarBase + 'LongPhan',
    department_id: 'dept-1', designation_id: 'des-4',
    status: 'active', work_type: 'full-time', work_location: 'Hà Nội HQ',
    gender: 'male', date_of_birth: '1987-07-11', date_of_joining: '2017-05-01',
    bio: 'Engineering Manager với 15+ năm kinh nghiệm, dẫn dắt team 20+ engineers.',
    departments: { id: 'dept-1', name: 'Kỹ thuật - Engineering', code: 'ENG' },
    designations: { id: 'des-4', title: 'Engineering Manager', level: 5 },
  },
  {
    id: 'emp-12', employee_id: 'EMP-012',
    full_name: 'Vũ Ngọc Mai', email: 'mai.vu@peoplehub.vn',
    phone: '0912345679', avatar_url: avatarBase + 'MaiVu',
    department_id: 'dept-6', designation_id: 'des-11',
    status: 'active', work_type: 'part-time', work_location: 'Remote',
    gender: 'female', date_of_birth: '1996-10-03', date_of_joining: '2023-03-15',
    bio: 'UX Designer bán thời gian, chuyên về motion design và prototyping.',
    departments: { id: 'dept-6', name: 'Thiết kế - Design', code: 'DESIGN' },
    designations: { id: 'des-11', title: 'UX Designer', level: 2 },
  },
]
